server:
  host: 0.0.0.0
  port: 8081
  workers: 8
  access_log: false
  debug: false
  ssl: false
  cert: /etc/letsencrypt/live/retriever-ocr.co.jp/fullchain.pem
  key: /etc/letsencrypt/live/retriever-ocr.co.jp/privkey.pem

asr_mq_name: cb_queue
upload_storage: data